# Generated by Django 4.1.2 on 2022-12-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=50)),
                ('valorUnitario', models.CharField(max_length=11)),
            ],
        ),
    ]
